# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirmPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from threading import Timer
from functools import partial

import create_data  
import function_db

db = function_db.db_function
createData = create_data.create

_translate = QtCore.QCoreApplication.translate
    # createData.initOrderPage(self , MainWindow)
def resetApp(self , MainWindow) :
    print("reset")
    createData.initOrderPage(self , MainWindow , "")
    self.BtMenu.click()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow , List , listMenuDB):
        
        self.confirm = QtWidgets.QWidget()
        self.confirm.setObjectName("confirm")
        self.list_report = QtWidgets.QScrollArea(self.confirm)
        self.list_report.setGeometry(QtCore.QRect(20, 70, 882, 440))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_report.sizePolicy().hasHeightForWidth())
        self.list_report.setSizePolicy(sizePolicy)
        self.list_report.setMinimumSize(QtCore.QSize(882, 440))
        self.list_report.setMaximumSize(QtCore.QSize(882, 440))
        self.list_report.setStyleSheet("background-color: #8b5234;")
        self.list_report.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_report.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_report.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.list_report.setObjectName("list_report")
        self.report_list = QtWidgets.QWidget()
        self.report_list.setGeometry(QtCore.QRect(0, 0, 880, 180 * len(List)))
        self.report_list.setMinimumSize(QtCore.QSize(0, 180))
        self.report_list.setStyleSheet("QFrame {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:0px;\n"
"    border-radius:32;\n"
"}")
        self.report_list.setObjectName("report_list")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.report_list)
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 11)
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        num = 1

        for key , detail in List.items() :
                menuDB = listMenuDB.get(key)
                self.listCoffeeReport = QtWidgets.QFrame(self.report_list)
                self.listCoffeeReport.setEnabled(True)
                self.listCoffeeReport.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.listCoffeeReport.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.listCoffeeReport.setFrameShadow(QtWidgets.QFrame.Raised)
                self.listCoffeeReport.setObjectName("listCoffeeReport")
                self.name_2 = QtWidgets.QLabel(self.listCoffeeReport)
                self.name_2.setGeometry(QtCore.QRect(20, 20, 571, 33))
                font = QtGui.QFont()
                font.setFamily("DSN Single")
                font.setPointSize(20)
                font.setBold(True)
                font.setWeight(75)
                self.name_2.setFont(font)
                self.name_2.setObjectName("name_2")
                self.textBath_2 = QtWidgets.QLabel(self.listCoffeeReport)
                self.textBath_2.setGeometry(QtCore.QRect(452, 110, 351, 41))
                font = QtGui.QFont()
                font.setFamily("DSN PatPong Extend")
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.textBath_2.setFont(font)
                self.textBath_2.setFrameShape(QtWidgets.QFrame.VLine)
                self.textBath_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
                self.textBath_2.setObjectName("textBath_2")
                self.iconBathReport = QtWidgets.QLabel(self.listCoffeeReport)
                self.iconBathReport.setGeometry(QtCore.QRect(810, 112, 35, 35))
                font = QtGui.QFont()
                font.setPointSize(5)
                self.iconBathReport.setFont(font)
                self.iconBathReport.setText("")
                self.iconBathReport.setPixmap(QtGui.QPixmap("Bath.png"))
                self.iconBathReport.setScaledContents(True)
                self.iconBathReport.setAlignment(QtCore.Qt.AlignCenter)
                self.iconBathReport.setObjectName("iconBathReport")
                self.imgReport = QtWidgets.QLabel(self.listCoffeeReport)
                self.imgReport.setGeometry(QtCore.QRect(728, 10, 75, 101))
                self.imgReport.setStyleSheet("* {\n"
        "    background-color: rgba(255, 255, 255, 0);\n"
        "    border:1.5 solid #8b5234;\n"
        "    border-radius:0px;\n"
        "}")
                self.imgReport.setInputMethodHints(QtCore.Qt.ImhNone)

                pix = QtGui.QPixmap()
                if pix.loadFromData(menuDB['img_menu']) :
                    self.img.setPixmap(pix)
                self.imgReport.setPixmap(pix)
                self.imgReport.setScaledContents(True)
                self.imgReport.setObjectName("imgReport")
                self.type_coffee_report = QtWidgets.QLabel(self.listCoffeeReport)
                self.type_coffee_report.setGeometry(QtCore.QRect(50, 50, 541, 61))
                font = QtGui.QFont()
                font.setFamily("DSN Single")
                font.setPointSize(18)
                self.type_coffee_report.setFont(font)
                self.type_coffee_report.setObjectName("type_coffee_report")
                self.qty_report = QtWidgets.QLabel(self.listCoffeeReport)
                self.qty_report.setGeometry(QtCore.QRect(50, 100, 551, 51))
                font = QtGui.QFont()
                font.setFamily("DSN Single")
                font.setPointSize(25)
                self.qty_report.setFont(font)
                self.qty_report.setObjectName("qty_report")
                self.verticalLayout_4.addWidget(self.listCoffeeReport)

                try :
                    taste = detail['taste']
                except :
                    taste = 'หวานปกติ'

                self.listCoffeeReport.setAccessibleName(_translate("MainWindow", "listcoffee"))
                self.name_2.setText(_translate("MainWindow", f"{num}. {menuDB['name_menu']}"))
                self.textBath_2.setText(_translate("MainWindow", f"ยอดรวม {int(detail['qty']) * menuDB['price_menu']}"))
                self.type_coffee_report.setText(_translate("MainWindow", taste))
                self.qty_report.setText(_translate("MainWindow", f"จำนวน {detail['qty']} แก้ว"))
                num += 1

        self.list_report.setWidget(self.report_list)
        self.header = QtWidgets.QFrame(self.confirm)
        self.header.setGeometry(QtCore.QRect(20, 20, 881, 51))
        self.header.setStyleSheet("* {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.Textheader = QtWidgets.QLabel(self.header)
        self.Textheader.setGeometry(QtCore.QRect(30, 0, 851, 51))
        font = QtGui.QFont()
        font.setFamily("DSN PreeCha")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Textheader.setFont(font)
        self.Textheader.setObjectName("Textheader")
        self.label_2 = QtWidgets.QLabel(self.header)
        self.label_2.setGeometry(QtCore.QRect(770, 0, 111, 51))
        font = QtGui.QFont()
        font.setFamily("DSN Single")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.boxTextReport = QtWidgets.QFrame(self.confirm)
        self.boxTextReport.setGeometry(QtCore.QRect(20, 510, 881, 51))
        self.boxTextReport.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.boxTextReport.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.boxTextReport.setFrameShadow(QtWidgets.QFrame.Raised)
        self.boxTextReport.setObjectName("boxTextReport")
        self.textReport = QtWidgets.QLabel(self.boxTextReport)
        self.textReport.setGeometry(QtCore.QRect(10, 0, 331, 51))
        font = QtGui.QFont()
        font.setFamily("DSN Single")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.textReport.setFont(font)
        self.textReport.setStyleSheet("* {\n"
"color:red;\n"
"}")
        self.textReport.setObjectName("textReport")
        self.resuitText = QtWidgets.QLabel(self.boxTextReport)
        self.resuitText.setGeometry(QtCore.QRect(474, 0, 391, 51))
        font = QtGui.QFont()
        font.setFamily("DSN Single")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.resuitText.setFont(font)
        self.resuitText.setStyleSheet("* {\n"
"    color:blue;\n"
"}")
        self.resuitText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.resuitText.setObjectName("resuitText")
        MainWindow.addTab(self.confirm, "")

        MainWindow.setCurrentIndex(0)

    def retranslateUi(self, MainWindow , List , ListDB , price) :
        db.addreceipt(List , ListDB , price)
        self.returnPage = QtWidgets.QPushButton(self.header)
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Textheader.setText(_translate("MainWindow", f"รายการทั้งหมด {len(List)} รายการ"))
        #------------------- set Delay Page ---------------------------------#
        showSecone(120 , self , MainWindow , self.label_2 , self.returnPage)
        #------------------- set Delay Page ---------------------------------#
        self.textReport.setText(_translate("MainWindow", "ชำระเงินที่หน้าเคาร์เตอร์"))
        self.resuitText.setText(_translate("MainWindow", f"ยอดรวมทั้งหมด {price} บาท"))
        MainWindow.setTabText(MainWindow.indexOf(self.confirm), _translate("MainWindow", "ใบเสร็จ"))

        self.returnPage.clicked.connect(partial(resetApp , self , MainWindow))
        self.BtMenu.clicked.connect(partial(clearTimer))

def clearTimer() :
    delay.cancel()

def showSecone(time , self , MainWindow , label , reset) :
    global delay
    if time == 0 :
        MainWindow.removeTab(0)
        reset.click()
    else :
        label.setText(_translate("MainWindow", f"รอ {time} s"))
        time -= 1
        print(time)
        delay = Timer(1.0 , showSecone , (time , self , MainWindow , label , reset))
        delay.start()

