# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'coffeeMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import confirm
from functools import partial
import create_data
createData = create_data.create



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        #--------set fonts--------------------------------------------------
        QtGui.QFontDatabase.addApplicationFont('assets/fonts/DSNANR_.TTF')
        QtGui.QFontDatabase.addApplicationFont('assets/fonts/DSNAPS_.TTF')
        QtGui.QFontDatabase.addApplicationFont('assets/fonts/DSNKAT_.TTF')
        QtGui.QFontDatabase.addApplicationFont('assets/fonts/DSNNK__.TTF')
        QtGui.QFontDatabase.addApplicationFont('assets/fonts/DSNPC__.TTF')
        QtGui.QFontDatabase.addApplicationFont('assets/fonts/DSNPPE_.TTF')
        QtGui.QFontDatabase.addApplicationFont('assets/fonts/DSNRBRN.TTF')
        QtGui.QFontDatabase.addApplicationFont('assets/fonts/DSNSIN_.TTF')
        QtGui.QFontDatabase.addApplicationFont('assets/fonts/DSNSSW_.TTF')
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1100, 695)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 695))
        MainWindow.setMaximumSize(QtCore.QSize(1100, 695))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.shopName = QtWidgets.QLabel(self.centralwidget)
        self.shopName.setGeometry(QtCore.QRect(0, -11, 218, 166))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.shopName.setFont(font)
        self.shopName.setStyleSheet("* {\n"
"color:white;\n"
"padding-top:-10px;\n"
"background-color:#8b5234;\n"
"border:0 solid;\n"
"}")
        self.shopName.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.shopName.setObjectName("shopName")
        self.bodyShop = QtWidgets.QTabWidget(self.centralwidget)
        self.bodyShop.setGeometry(QtCore.QRect(0, 0, 1101, 697))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bodyShop.sizePolicy().hasHeightForWidth())
        self.bodyShop.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DSN NamKang")
        font.setPointSize(26)
        font.setKerning(True)
        self.bodyShop.setFont(font)
        self.bodyShop.setStyleSheet("QTabBar::tab{\n"
"    border-top:1px solid  rgb(218, 209, 192);\n"
"    width:217.5;\n"
"    height:179;\n"
"    background-color:white;\n"
"color: rgba(255, 255, 255, 0);"
"}\n"
"\n"
"QTabBar::tab:selected{\n"
"    background-color: #f4ac7d;\n"
"}\n"
"\n"
"QTabBar::tab:first\n"
"{\n"
"    margin:155 0 0 0;\n"
"}\n"
"\n"
"QWidget:pane{\n"
"}\n"
"\n"
"")
        self.bodyShop.setTabPosition(QtWidgets.QTabWidget.West)
        self.bodyShop.setIconSize(QtCore.QSize(20, 20))
        self.bodyShop.setObjectName("bodyShop")
        self.allmenu = QtWidgets.QWidget()
        self.allmenu.setStyleSheet("")
        self.allmenu.setObjectName("allmenu")
        self.menu_sell = QtWidgets.QTabWidget(self.allmenu)
        self.menu_sell.setGeometry(QtCore.QRect(0, -2, 881, 711))
        font = QtGui.QFont()
        font.setFamily("DSN SukSaWat")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.menu_sell.setFont(font)
        self.menu_sell.setStyleSheet("::tab{\n"
"    background-color:#8b5234;\n"
"    border-left:1px solid rgb(218, 209, 192);\n"
"}\n"
"\n"
"\n"
"QTabBar::tab{\n"
"    width:216;\n"
"    height:156;\n"
"    margin:0;\n"
"    color:white;\n"
"}\n"
"\n"
"QTabBar::tab:selected{\n"
"    padding-bottom:5px;\n"
"    padding-top:-5px;\n"
"}\n"
"\n"
"QWidget:pane{\n"
"    padding:-19;\n"
"}")
        self.menu_sell.setObjectName("menu_sell")

        self.coffee = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("DSN AmPun Solid")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.coffee.setFont(font)
        self.coffee.setStyleSheet("font-size:16;")
        self.coffee.setObjectName("coffee")
        self.listCoffee = QtWidgets.QScrollArea(self.coffee)
        self.listCoffee.setGeometry(QtCore.QRect(20, 20, 882, 541))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listCoffee.sizePolicy().hasHeightForWidth())
        self.listCoffee.setSizePolicy(sizePolicy)
        self.listCoffee.setMinimumSize(QtCore.QSize(882, 541))
        self.listCoffee.setMaximumSize(QtCore.QSize(882, 541))
        self.listCoffee.setStyleSheet("background-color: #8b5234;")
        self.listCoffee.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listCoffee.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listCoffee.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.listCoffee.setObjectName("listCoffee")
        self.list = QtWidgets.QWidget()
        self.list.setGeometry(QtCore.QRect(0, 0, 880, 193))
        self.list.setMinimumSize(QtCore.QSize(0, 193))
        self.list.setStyleSheet("QFrame {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:0px;\n"
"    border-radius:32;\n"
"}")
        self.list.setObjectName("list")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.list)
        self.verticalLayout.setObjectName("verticalLayout")
        #menu list coffee------------------------------------------------------------
        
        #----------------------------------------------------------------------
        self.listCoffee.setWidget(self.list)
        self.menu_sell.addTab(self.coffee, "")


        self.ice_drink = QtWidgets.QWidget()
        self.ice_drink.setObjectName("ice_drink")
        self.listIce_drink = QtWidgets.QScrollArea(self.ice_drink)
        self.listIce_drink.setGeometry(QtCore.QRect(20, 20, 882, 541))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listIce_drink.sizePolicy().hasHeightForWidth())
        self.listIce_drink.setSizePolicy(sizePolicy)
        self.listIce_drink.setMinimumSize(QtCore.QSize(882, 541))
        self.listIce_drink.setMaximumSize(QtCore.QSize(882, 16777215))
        self.listIce_drink.setStyleSheet("background-color:#8b5234;")
        self.listIce_drink.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listIce_drink.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listIce_drink.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.listIce_drink.setObjectName("listIce_drink")
        self.menu_ice = QtWidgets.QWidget()
        self.menu_ice.setGeometry(QtCore.QRect(0, 0, 880, 193))
        self.menu_ice.setMinimumSize(QtCore.QSize(0, 193))
        self.menu_ice.setStyleSheet("QFrame {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:0px;\n"
"    border-radius:32;\n"
"}")
        self.menu_ice.setObjectName("menu_ice")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.menu_ice)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        #Menu list ice-------------------------------------------------------------------
        
        #--------------------------------------------------------------------------

        self.listIce_drink.setWidget(self.menu_ice)
        self.menu_sell.addTab(self.ice_drink, "")

        self.fluit_drink = QtWidgets.QWidget()
        self.fluit_drink.setObjectName("fluit_drink")
        self.listfluit_drink = QtWidgets.QScrollArea(self.fluit_drink)
        self.listfluit_drink.setGeometry(QtCore.QRect(20, 20, 882, 541))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listfluit_drink.sizePolicy().hasHeightForWidth())
        self.listfluit_drink.setSizePolicy(sizePolicy)
        self.listfluit_drink.setMinimumSize(QtCore.QSize(882, 541))
        self.listfluit_drink.setMaximumSize(QtCore.QSize(882, 16777215))
        self.listfluit_drink.setStyleSheet("background-color:#8b5234;\n"
"")
        self.listfluit_drink.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listfluit_drink.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listfluit_drink.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.listfluit_drink.setObjectName("listfluit_drink")
        self.menu_fluit = QtWidgets.QWidget()
        self.menu_fluit.setGeometry(QtCore.QRect(0, 0, 880, 193))
        self.menu_fluit.setMinimumSize(QtCore.QSize(0, 193))
        self.menu_fluit.setStyleSheet("QFrame {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:0px;\n"
"    border-radius:32;\n"
"}")
        self.menu_fluit.setObjectName("menu_fluit")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.menu_fluit)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        #menu list fruit-------------------------------------------------
        
        #----------------------------------------------------------------
        self.listfluit_drink.setWidget(self.menu_fluit)
        self.menu_sell.addTab(self.fluit_drink, "")
        self.bodyShop.addTab(self.allmenu, "")
        self.order = QtWidgets.QWidget()
        self.order.setObjectName("order")
        self.menu_order = QtWidgets.QTabWidget(self.order)
        self.menu_order.setGeometry(QtCore.QRect(0, -2, 881, 701))
        font = QtGui.QFont()
        font.setFamily("DSN SukSaWat")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.menu_order.setFont(font)
        self.menu_order.setStyleSheet("::tab{\n"
"    background-color:#8b5234;\n"
"    border-left:1 solid rgb(218, 209, 192);\n"
"    border-right:1 solid rgb(218, 209, 192);\n"
"}\n"
"\n"
"\n"
"QTabBar::tab{\n"
"    width:648;\n"
"    height:156;\n"
"    margin:0;\n"
"    color:white;\n"
"}\n"
"\n"
"QTabBar::tab:selected{\n"
"    border-left:0.5 solid rgb(255, 255, 255);\n"
"    border-right:0.5 solid rgb(255, 255, 255);\n"
"}\n"
"\n"
"QWidget:pane{\n"
"    padding:-19;\n"
"}")
        self.menu_order.setObjectName("menu_order")
        #------------------------------------------------------------------------------------
        #------------------------------------menu page---------------------------------------
        #------------------------------------------------------------------------------------
        self.bodyShop.addTab(self.order, "")
        self.about_me = QtWidgets.QWidget()
        self.about_me.setObjectName("about_me")
        self.about_page = QtWidgets.QTabWidget(self.about_me)
        self.about_page.setGeometry(QtCore.QRect(0, -2, 881, 701))
        font = QtGui.QFont()
        font.setFamily("DSN SukSaWat")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.about_page.setFont(font)
        self.about_page.setStyleSheet("::tab{\n"
"    background-color:#8b5234;\n"
"    border-left:1 solid rgb(218, 209, 192);\n"
"    border-right:1 solid rgb(218, 209, 192);\n"
"}\n"
"\n"
"\n"
"QTabBar::tab{\n"
"    width:648;\n"
"    height:156;\n"
"    margin:0;\n"
"    color:white;\n"
"}\n"
"\n"
"QTabBar::tab:selected{\n"
"    border-left:0.5 solid rgb(255, 255, 255);\n"
"    border-right:0.5 solid rgb(255, 255, 255);\n"
"}\n"
"\n"
"QWidget:pane{\n"
"    padding:-19;\n"
"}\n"
"")
        self.about_page.setObjectName("about_page")
        self.member = QtWidgets.QWidget()
        self.member.setObjectName("member")
        self.frame = QtWidgets.QFrame(self.member)
        self.frame.setGeometry(QtCore.QRect(20, 20, 881, 541))
        self.frame.setStyleSheet("* {\n"
"    background-color:#8b5234;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setSpacing(18)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.thanawat = QtWidgets.QFrame(self.frame)
        self.thanawat.setStyleSheet("* {\n"
"    background-color: white;\n"
"    border:1px solid transparent;\n"
"    border-radius:50;\n"
"}")
        self.thanawat.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.thanawat.setFrameShadow(QtWidgets.QFrame.Raised)
        self.thanawat.setObjectName("thanawat")
        self.imgTha = QtWidgets.QLabel(self.thanawat)
        self.imgTha.setGeometry(QtCore.QRect(150, 10, 111, 141))
        self.imgTha.setStyleSheet("* {\n"
"    border:0px solid;\n"
"    border-radius:0px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.imgTha.setText("")
        self.imgTha.setPixmap(QtGui.QPixmap("assets/img_shop/tha.jpg"))
        self.imgTha.setScaledContents(True)
        self.imgTha.setObjectName("imgTha")
        self.detailTha = QtWidgets.QFrame(self.thanawat)
        self.detailTha.setGeometry(QtCore.QRect(400, 0, 461, 161))
        self.detailTha.setStyleSheet("* {\n"
"    border:0px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.detailTha.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.detailTha.setFrameShadow(QtWidgets.QFrame.Raised)
        self.detailTha.setObjectName("detailTha")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.detailTha)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.number1 = QtWidgets.QLabel(self.detailTha)
        font = QtGui.QFont()
        font.setFamily("DSN PreeCha")
        font.setPointSize(20)
        self.number1.setFont(font)
        self.number1.setStyleSheet("* {\n"
"background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.number1.setObjectName("number1")
        self.verticalLayout_7.addWidget(self.number1)
        self.name1 = QtWidgets.QLabel(self.detailTha)
        font = QtGui.QFont()
        font.setFamily("DSN PreeCha")
        font.setPointSize(20)
        self.name1.setFont(font)
        self.name1.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.name1.setObjectName("name1")
        self.verticalLayout_7.addWidget(self.name1)
        self.faculty = QtWidgets.QLabel(self.detailTha)
        font = QtGui.QFont()
        font.setFamily("DSN PreeCha")
        font.setPointSize(20)
        self.faculty.setFont(font)
        self.faculty.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"")
        self.faculty.setObjectName("faculty")
        self.verticalLayout_7.addWidget(self.faculty)
        self.verticalLayout_6.addWidget(self.thanawat)
        self.chattaporn = QtWidgets.QFrame(self.frame)
        self.chattaporn.setStyleSheet("* {\n"
"    background-color: white;\n"
"    border:1px solid transparent;\n"
"    border-radius:50;\n"
"}")
        self.chattaporn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chattaporn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chattaporn.setObjectName("chattaporn")
        self.imgChat = QtWidgets.QLabel(self.chattaporn)
        self.imgChat.setGeometry(QtCore.QRect(150, 10, 111, 141))
        self.imgChat.setStyleSheet("* {\n"
"    border:0px solid;\n"
"    border-radius:0px;\n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.imgChat.setText("")
        self.imgChat.setPixmap(QtGui.QPixmap("assets/img_shop/chat.jpg"))
        self.imgChat.setScaledContents(True)
        self.imgChat.setObjectName("imgChat")
        self.detailChat = QtWidgets.QFrame(self.chattaporn)
        self.detailChat.setGeometry(QtCore.QRect(400, 0, 451, 161))
        self.detailChat.setStyleSheet("* {\n"
"    border:0px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.detailChat.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.detailChat.setFrameShadow(QtWidgets.QFrame.Raised)
        self.detailChat.setObjectName("detailChat")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.detailChat)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.name2 = QtWidgets.QLabel(self.detailChat)
        font = QtGui.QFont()
        font.setFamily("DSN PreeCha")
        font.setPointSize(20)
        self.name2.setFont(font)
        self.name2.setStyleSheet("* {\n"
"background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.name2.setObjectName("name2")
        self.verticalLayout_8.addWidget(self.name2)
        self.number2 = QtWidgets.QLabel(self.detailChat)
        font = QtGui.QFont()
        font.setFamily("DSN PreeCha")
        font.setPointSize(20)
        self.number2.setFont(font)
        self.number2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.number2.setObjectName("number2")
        self.verticalLayout_8.addWidget(self.number2)
        self.faculty2 = QtWidgets.QLabel(self.detailChat)
        font = QtGui.QFont()
        font.setFamily("DSN PreeCha")
        font.setPointSize(20)
        self.faculty2.setFont(font)
        self.faculty2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"")
        self.faculty2.setObjectName("faculty2")
        self.verticalLayout_8.addWidget(self.faculty2)
        self.verticalLayout_6.addWidget(self.chattaporn)
        self.ketaphat = QtWidgets.QFrame(self.frame)
        self.ketaphat.setStyleSheet("* {\n"
"    background-color: white;\n"
"    border:1px solid transparent;\n"
"    border-radius:50;\n"
"}")
        self.ketaphat.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ketaphat.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ketaphat.setObjectName("ketaphat")
        self.imgKe = QtWidgets.QLabel(self.ketaphat)
        self.imgKe.setGeometry(QtCore.QRect(150, 10, 111, 141))
        self.imgKe.setStyleSheet("* {\n"
"    border:0px solid;\n"
"    border-radius:0px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.imgKe.setText("")
        self.imgKe.setPixmap(QtGui.QPixmap("assets/img_shop/kee.jpg"))
        self.imgKe.setScaledContents(True)
        self.imgKe.setObjectName("imgKe")
        self.detailKe = QtWidgets.QFrame(self.ketaphat)
        self.detailKe.setGeometry(QtCore.QRect(400, 0, 451, 161))
        self.detailKe.setStyleSheet("* {\n"
"    border:0px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.detailKe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.detailKe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.detailKe.setObjectName("detailKe")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.detailKe)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.name3 = QtWidgets.QLabel(self.detailKe)
        font = QtGui.QFont()
        font.setFamily("DSN PreeCha")
        font.setPointSize(20)
        self.name3.setFont(font)
        self.name3.setStyleSheet("* {\n"
"background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.name3.setObjectName("name3")
        self.verticalLayout_9.addWidget(self.name3)
        self.number3 = QtWidgets.QLabel(self.detailKe)
        font = QtGui.QFont()
        font.setFamily("DSN PreeCha")
        font.setPointSize(20)
        self.number3.setFont(font)
        self.number3.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.number3.setObjectName("number3")
        self.verticalLayout_9.addWidget(self.number3)
        self.faculty3 = QtWidgets.QLabel(self.detailKe)
        font = QtGui.QFont()
        font.setFamily("DSN PreeCha")
        font.setPointSize(20)
        self.faculty3.setFont(font)
        self.faculty3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"")
        self.faculty3.setObjectName("faculty3")
        self.verticalLayout_9.addWidget(self.faculty3)
        self.verticalLayout_6.addWidget(self.ketaphat)
        self.about_page.addTab(self.member, "")
        self.bodyShop.addTab(self.about_me, "")
        self.searchText = QtWidgets.QLineEdit(self.centralwidget)
        self.searchText.setGeometry(QtCore.QRect(880, 50, 200, 55))
        self.searchText.setMaximumSize(QtCore.QSize(200, 55))
        font = QtGui.QFont()
        font.setFamily("DSN RatBuRaNa")
        font.setPointSize(27)
        self.searchText.setFont(font)
        self.searchText.setStyleSheet("border:1 solid rgba(188, 188, 188, 100);\n"
"border-radius:25px; \n"
"background-color: palette(base);\n"
"padding-left:10;")
        self.searchText.setFrame(True)
        self.searchText.setDragEnabled(False)
        self.searchText.setClearButtonEnabled(False)
        self.searchText.setObjectName("searchText")
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(1030, 50, 61, 55))
        self.searchButton.setStyleSheet("#searchButton {\n"
"    border-left:1.5 solid rgba(188, 188, 188, 100);\n"
"    border-top-right-radius:25px; \n"
"    border-bottom-right-radius:25px; \n"
"    background-color: palette(base);\n"
"}\n"
" \n"
"#searchButton:pressed {\n"
"    border:1.5 solid rgba(188, 188, 188, 100);\n"
"    background-color:#f4ac7d;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/img_shop/loupe.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.searchButton.setIcon(icon)
        self.searchButton.setIconSize(QtCore.QSize(30, 30))
        self.searchButton.setObjectName("searchButton")
        self.bodyShop.raise_()
        self.shopName.raise_()
        self.searchText.raise_()
        self.searchButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.BtMenu = QtWidgets.QPushButton(self.centralwidget)
        self.BtMenu.setGeometry(QtCore.QRect(-3, 154, 223, 183))
        font = QtGui.QFont()
        font.setFamily("DSN SukSaWat")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.BtMenu.setFont(font)
        self.BtMenu.setStyleSheet("* {\n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.BtMenu.setObjectName("BtMenu")

        self.BtOrder = QtWidgets.QPushButton(self.centralwidget)
        self.BtOrder.setGeometry(QtCore.QRect(-3, 334, 223, 183))
        font = QtGui.QFont()
        font.setFamily("DSN SukSaWat")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.BtOrder.setFont(font)
        self.BtOrder.setStyleSheet("* {\n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.BtOrder.setObjectName("BtOrder")

        self.BtAbout = QtWidgets.QPushButton(self.centralwidget)
        self.BtAbout.setGeometry(QtCore.QRect(-3, 517, 223, 183))
        font = QtGui.QFont()
        font.setFamily("DSN SukSaWat")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.BtAbout.setFont(font)
        self.BtAbout.setStyleSheet("* {\n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.BtAbout.setObjectName("BtAbout")

        self.BtMenu.raise_()
        self.BtOrder.raise_()
        self.BtAbout.raise_()

        self.retranslateUi(MainWindow)
        self.bodyShop.setCurrentIndex(1)
        self.menu_sell.setCurrentIndex(0)
        self.menu_order.setCurrentIndex(0)
        self.about_page.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Coffee shop"))
        self.shopName.setText(_translate("MainWindow", "Coffee Shop"))
        self.bodyShop.setAccessibleName(_translate("MainWindow", "bodyShop"))
        self.allmenu.setAccessibleName(_translate("MainWindow", "allmenu"))
        self.menu_sell.setAccessibleName(_translate("MainWindow", "menu_sell"))
        self.coffee.setAccessibleName(_translate("MainWindow", "coffee"))
        
        self.menu_sell.setTabText(self.menu_sell.indexOf(self.coffee), _translate("MainWindow", "กาแฟ"))
        
        self.menu_sell.setTabText(self.menu_sell.indexOf(self.ice_drink), _translate("MainWindow", "เครื่องดื่มเย็น"))
        
        self.menu_sell.setTabText(self.menu_sell.indexOf(self.fluit_drink), _translate("MainWindow", "เมนูน้ำผลไม้"))

        self.bodyShop.setTabText(self.bodyShop.indexOf(self.allmenu), _translate("MainWindow", "MENU"))
        self.order.setAccessibleName(_translate("MainWindow", "order"))
        
        self.bodyShop.setTabText(self.bodyShop.indexOf(self.order), _translate("MainWindow", "ORDER"))
        self.about_me.setAccessibleName(_translate("MainWindow", "about_me"))
        self.number1.setText(_translate("MainWindow", "นายธนวัฒน์ เอี่ยมละออ"))
        self.name1.setText(_translate("MainWindow", "รหัสนักศึกษา 116310400590-0"))
        self.faculty.setText(_translate("MainWindow", "คณะวิศวกรรมศาสตร์ สาขาคอมพิวเตอร์"))
        self.name2.setText(_translate("MainWindow", "นางสาวฉัตรพร แก้วเฉลิม"))
        self.number2.setText(_translate("MainWindow", "รหัสนักศึกษา 116310400245-1"))
        self.faculty2.setText(_translate("MainWindow", "คณะวิศวกรรมศาสตร์ สาขาคอมพิวเตอร์"))
        self.name3.setText(_translate("MainWindow", "นางสาวคีตะภัทร ภิบาล "))
        self.number3.setText(_translate("MainWindow", "รหัสนักศึกษา 116310462005-4"))
        self.faculty3.setText(_translate("MainWindow", "คณะวิศวกรรมศาสตร์ สาขาคอมพิวเตอร์"))
        self.about_page.setTabText(self.about_page.indexOf(self.member), _translate("MainWindow", "สมาชิกกลุ่ม"))
        self.bodyShop.setTabText(self.bodyShop.indexOf(self.about_me), _translate("MainWindow", "ABOUNT US"))
        self.searchText.setAccessibleName(_translate("MainWindow", "search"))
        self.searchText.setPlaceholderText(_translate("MainWindow", "ค้นหาเมนู"))
        self.searchButton.setAccessibleName(_translate("MainWindow", "searchButton"))

        def changeTab(page) :
            xnum = 1
            textReset = ""
            for x in self.menu_order.children()[0].children() :
                if xnum == len(self.menu_order.children()[0].children()) :
                    if x.objectName() == 'confirm' :
                        print("reset A")
                        textReset = "reset A"
                        createData.initOrderPage(self , self.menu_order , "0x048")
                    if textReset == "reset A" :
                        x.deleteLater()
                xnum += 1
            if page == 0 :
                self.searchText.setReadOnly(False)
            else :
                self.searchText.setReadOnly(True)
            self.bodyShop.setCurrentIndex(page)

        def search() :
            self.menu_order.removeTab(0)
            if self.searchText.text() != "" :
                createData.initOrderPage(self , self.menu_order , self.searchText.text())
            else :
                createData.initOrderPage(self , self.menu_order , "444")
            self.searchText.setText(_translate("MainWindow", ""))
        
        self.BtMenu.setText(_translate("MainWindow", "MENU"))
        self.BtOrder.setText(_translate("MainWindow", "ORDER"))
        self.BtAbout.setText(_translate("MainWindow", "ABOUT US"))

        self.BtMenu.clicked.connect(partial(changeTab , 0))
        self.BtOrder.clicked.connect(partial(changeTab , 1))
        self.BtAbout.clicked.connect(partial(changeTab , 2))

        self.searchButton.clicked.connect(partial(search))

        createData.initOrderPage(self , self.menu_order , "")
        





